<ns2:action>
    <ns2:actionID>100</ns2:actionID>
    <ns2:parameter>
        <ns2:key>thermostatID</ns2:key>
        <ns2:value>${thermostatId}</ns2:value>
    </ns2:parameter>
    <ns2:parameter>
        <ns2:key>setpoint</ns2:key>
        <ns2:value>${setpoint?c}</ns2:value>
    </ns2:parameter>
</ns2:action>