<constraints>
    <timeConstraint>
        <start>
            <exactTime>${startTimeString}</exactTime>
        </start>
        <end>
            <exactTime>${endTimeString}</exactTime>
        </end>
    </timeConstraint>
</constraints>